version: '3'

services:
    mysql:
        image: mysql:8
        environment:
            MYSQL_DATABASE: board
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - "3306:3306"
